[2024-10-06 06:39:43,629][utils.utils][ERROR] - Exception occurred during task execution.
Traceback (most recent call last):
  File "/workspace/Session-4-pytorch-lightning/src/utils/utils.py", line 12, in wrap
    return task_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/src/eval.py", line 32, in eval
    cfg = OmegaConf.to_container(cfg, resolve=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/omegaconf.py", line 573, in to_container
    return BaseContainer._to_content(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/basecontainer.py", line 292, in _to_content
    value = get_node_value(key)
            ^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/basecontainer.py", line 247, in get_node_value
    value = BaseContainer._to_content(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/basecontainer.py", line 292, in _to_content
    value = get_node_value(key)
            ^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/basecontainer.py", line 244, in get_node_value
    conf._format_and_raise(key=key, value=None, cause=e)
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/basecontainer.py", line 242, in get_node_value
    node = node._dereference_node()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/base.py", line 246, in _dereference_node
    node = self._dereference_node_impl(throw_on_resolution_failure=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/base.py", line 277, in _dereference_node_impl
    return parent._resolve_interpolation_from_parse_tree(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/base.py", line 769, in resolve_parse_tree
    raise InterpolationResolutionError(
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/grammar_visitor.py", line 298, in visitText
    return self.visitInterpolation(c)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1041, in accept
    return visitor.visitInterpolationResolver(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/grammar_visitor.py", line 179, in visitInterpolationResolver
    return self.resolver_interpolation_callback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/base.py", line 750, in resolver_interpolation_callback
    return self._evaluate_custom_resolver(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/base.py", line 694, in _evaluate_custom_resolver
    return resolver(
           ^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/omegaconf.py", line 445, in resolver_wrapper
    ret = resolver(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/omegaconf/resolvers/oc/__init__.py", line 38, in env
    raise KeyError(f"Environment variable '{key}' not found")
omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable 'GDRIVE_URL' not found"
    full_key: data.gdrive_url
    object_type=dict
[2024-10-06 06:39:43,632][utils.utils][INFO] - Task completed. Check the logs folder for details.
