[2024-10-06 05:17:11,210][__main__][INFO] - Current working directory: /workspace/Session-4-pytorch-lightning
[2024-10-06 05:17:11,210][__main__][INFO] - Configuration keys: dict_keys(['data', 'paths'])
[2024-10-06 05:17:11,211][__main__][INFO] - Paths configuration: root_dir: /workspace/Session-4-pytorch-lightning
data_dir: /workspace/Session-4-pytorch-lightning/data/
log_dir: /workspace/Session-4-pytorch-lightning/logs/
output_dir: /workspace/Session-4-pytorch-lightning/outputs/2024-10-06/05-17-11
work_dir: /workspace/Session-4-pytorch-lightning

[2024-10-06 05:17:11,212][__main__][INFO] - Data configuration: _target_: src.datamodules.dog_breed.DogBreedDataModule
gdrive_url: https://drive.google.com/file/d/15Yk-AaufO41Ocs-mnbgBCW46SsQRFlAI/view?usp=sharing
dl_path: /workspace/Session-4-pytorch-lightning/data//dataset/
train_val_test_split:
- 0.8
- 0.1
- 0.1
batch_size: 32
num_workers: 4
pin_memory: false
seed: 42

[2024-10-06 05:17:11,216][__main__][INFO] - Train Dataset Size: 773
[2024-10-06 05:17:11,216][__main__][INFO] - Validation Dataset Size: 96
[2024-10-06 05:17:11,216][__main__][INFO] - Test Dataset Size: 98
[2024-10-06 05:17:11,216][__main__][INFO] - Class Names: ['Beagle', 'Boxer', 'Bulldog', 'Dachshund', 'German_Shepherd', 'Golden_Retriever', 'Labrador_Retriever', 'Poodle', 'Rottweiler', 'Yorkshire_Terrier']
[2024-10-06 05:17:11,346][timm.models._builder][INFO] - Loading pretrained weights from Hugging Face hub (timm/resnet18.a1_in1k)
[2024-10-06 05:17:11,902][timm.models._hub][INFO] - [timm/resnet18.a1_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
[2024-10-06 05:17:11,912][timm.models._builder][INFO] - Missing keys (fc.weight, fc.bias) discovered while loading pretrained weights. This is expected if model is being adapted.
[2024-10-06 05:17:11,936][utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2024-10-06 05:17:11,936][utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2024-10-06 05:17:11,936][utils.rich_utils][WARNING] - Field 'paths' not found in config. Skipping 'paths' config printing...
[2024-10-06 05:17:11,936][utils.rich_utils][WARNING] - Field 'extras' not found in config. Skipping 'extras' config printing...
[2024-10-06 05:17:11,979][utils.utils][ERROR] - Exception occurred during task execution.
Traceback (most recent call last):
  File "/workspace/Session-4-pytorch-lightning/src/utils/utils.py", line 12, in wrap
    return task_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/src/train.py", line 84, in train
    print_config_tree(config, resolve=True, save_to_file=True)
  File "/workspace/Session-4-pytorch-lightning/src/utils/rich_utils.py", line 71, in print_config_tree
    with open(Path("/workspace/lightning-template-hydra/src/logs", "config_tree.log"), "w") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/lightning-template-hydra/src/logs/config_tree.log'
[2024-10-06 05:17:11,980][utils.utils][INFO] - Task completed. Check the logs folder for details.
